apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        location /api/ {
            proxy_pass http://jsonplaceholder.typicode.com/posts/;
        }
        location /hijo/ {
            proxy_pass http://youtube.com/;
        }
      }
    }
